### PR TITLE
requests in server/index.js

### PR DESCRIPTION
**Pull request by piercekg**
added axios for making requests, added server as const for making reqs, wrote getRelatedProducts req

### CODE REVIEW

**Review by htwest — COMMENTED** [review]
Looks good to me!

**Comment by piercekg** [comment]
just added a couple lines to client/requests.js, same thing: require('axios') and const server = localhost:300 for now

**Comment by dgoelitz** [comment]
OK, it looks fine. Go ahead and merge!

**Comment by piercekg** [comment]
k here goes

**Pull request merged**
