### PR TITLE
basic widget functionality

### PR DESCRIPTION
**Pull request by piercekg**
I think I mostly resolved the conflicts with my branch. check the requests and server/index.js to make sure nothing breaks things you're working on

### CODE REVIEW

**Review by htwest — COMMENTED** [review]
I think everything looks good!

**Comment by dgoelitz** [comment]
I think we're good to go here. Wow, coverage sure writes a ton of code. And so did you, great work!

**Review by dgoelitz — APPROVED** [review]
Good to go!

**Comment by piercekg** [comment]
Yeah I added coverage to gitignore when i saw that

**Pull request merged**
