### PR TITLE
Fleshed out web app files.

### PR DESCRIPTION
**Pull request by benkennedy98**
This is our base setup for the file structure.

### CODE REVIEW

**Review by htwest — COMMENTED** [review]
Looks good!

**Comment by benkennedy98** [comment]
Awesome glad you liked it I think it's ready for a second pass!

**Comment by htwest** [comment]
> Awesome glad you liked it I think it's ready for a second pass!

Second pass good!

**Comment by benkennedy98** [comment]
Hey @piercekg  or @dgoelitz I think this is ready for a third pass!

**Comment by dgoelitz** [comment]
I don't see any problems. Go ahead and merge the request!

**Pull request merged**
